### ISSUE TITLE
Issue Syncing VMs

### ISSUE THREAD

**Issue by adparis99** [jysk-oss/netbox-securecrt-inventory#12]
Hello,

I am running NetBox v4.1.0 and securecrt-inventory 0.3.3. When I start a new sync and open SecureCRT, I can see all of the devices I expect to see, but no VMs (despite the log saying that it found 100+ of them). My configuration file is below. Any thoughts on why this might be? For what it's worth, all VMs have an assigned tenant, which is why I am grouping that way.

```yaml
log_level: DEBUG
netbox_url: netbox.com
netbox_token: abcdefg
root_path: NB
session:
    path: '{tenant_name}'
    device_name: '{device_name}'
    session_options:
        connection_protocol: SSH
        credential: me
        firewall: None
    overrides: []
periodic_sync_enable: false
periodic_sync_interval: 120

```
